[package]
name = "planetary"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
bytemuck = "1.23.1"
glam = "0.30.4"
pollster = "0.4.0"
rand = "0.9.1"
wgpu = "25.0.2"
winit = "0.30.11"
